Include asm/sgidefs.h on non-glibc systems
sgidefs.h wrapper is glibc specific and causes build
failures on musl

Fixes
Platform.h:380:10: fatal error: sgidefs.h: No such file or directory
 #include <sgidefs.h>
          ^~~~~~~~~~~
compilation terminated.

Upstream-Status: Pending
Signed-off-by: Khem Raj <raj.khem@gmail.com>